### ISSUE TITLE
Code still valid?

### ISSUE THREAD

**Issue by simonarabian** [skyguy126/MomondoMiner#3]
Hi

A quick search provides the following api link with different methods: https://www.momondo.com/Momondo.asmx?

I wasn't able to find any documentation for "api v3". Could you please provide a link? Also, could you please update whether your code is code is still valid?

Thanks,
Simon

**Comment by skyguy126** [comment]
@slix88 Hey

So that link is actually a very very old API and the code in here isn't even meant for that. I just reverse engineered the requests being sent back and forth with networking tools on chrome and mimicked that in python. It looks like their way of fetching data has changed quite drastically and the program would need a complete rewrite for it to work correctly. Unfortunately as of now I don't see myself updating it in the near future.

Thanks for reaching out!
